
/* Drop Tables */

DROP TABLE ADVICE CASCADE CONSTRAINTS;
DROP TABLE BASKET CASCADE CONSTRAINTS;
DROP TABLE ITEM CASCADE CONSTRAINTS;
DROP TABLE MEMBER_INFO CASCADE CONSTRAINTS;
DROP TABLE NOTI CASCADE CONSTRAINTS;
DROP TABLE ORDER_LIST CASCADE CONSTRAINTS;
DROP TABLE QnA_BOARD CASCADE CONSTRAINTS;
DROP TABLE REPLY CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;


/* Select Tables */

Select * from advice;
Select * from basket;
Select * from item;
Select * from member_info;
Select * from noti;
Select * from order_list;
Select * from qna_board;
Select * from reply;
Select * from review;


/* Create Tables */

CREATE TABLE ADVICE
(
	ADVICE_MEMBER_EMAIL varchar2(35) NOT NULL UNIQUE,
	ADVICE_MEMBER_NAME varchar2(20) NOT NULL,
	ADVICE_MEMBER_TEL varchar2(20) NOT NULL,
	ADVICE_CONTENT varchar2(2000) NOT NULL,
	ADVICE_DATE date NOT NULL
);


CREATE TABLE BASKET
(
	BASKET_MEMBER_EMAIL varchar2(35) NOT NULL UNIQUE,
	BASKET_MEMBER_NAME varchar2(20) NOT NULL,
	BASKET_ITEM_NAME varchar2(50) NOT NULL UNIQUE,
	BASKET_ITEM_PRICE varchar2(10) NOT NULL,
	BASKET_ITEM_IMAGE varchar2(50) NOT NULL,
	BASKET_ITEM_BRAND varchar2(50) NOT NULL,
	BASKET_DATE date NOT NULL,
	BASKET_AMOUNT number(5) NOT NULL,
	BASKET_RESULT number(10) NOT NULL,
	BASKET_ITEM_MODEL varchar2(200) NOT NULL
);


CREATE TABLE ITEM
(
	ITEM_MODEL varchar2(50) NOT NULL UNIQUE,
	ITEM_NAME varchar2(50) NOT NULL UNIQUE,
	ITEM_PRICE number(10) NOT NULL,
	ITEM_IMAGE varchar2(50) NOT NULL,
	ITEM_TYPE varchar2(20) NOT NULL,
	ITEM_BRAND varchar2(50) NOT NULL,
	ITEM_CONTENT varchar2(2000) NOT NULL
);


CREATE TABLE MEMBER_INFO
(
	MEMBER_NAME varchar2(20) NOT NULL,
	MEMBER_EMAIL varchar2(35) NOT NULL UNIQUE,
	MEMBER_PWD varchar2(30) NOT NULL,
	MEMBER_ADDR_1 varchar2(50) NOT NULL,
	MEMBER_ADDR_2 varchar2(50) NOT NULL,
	MEMBER_ADDR_ZIP varchar2(10) NOT NULL,
	MEMBER_TEL varchar2(20) NOT NULL,
	MEMBER_GENDER varchar2(5) NOT NULL,
	MEMBER_BIRTH varchar2(20) NOT NULL,
	MEMBER_DATE date NOT NULL
);


CREATE TABLE NOTI
(
	NOTI_MEMBER_EMAIL varchar2(35),
	NOTI_MEMBER_NAME varchar2(20),
	NOTI_SUBJECT varchar2(100),
	NOTI_CONTENT varchar2(2000),
	NOTI_READCOUNT number(5),
	NOTI_DATE date,
	NOTI_NUM number(10),
	NOTI_FILE varchar2(50)
);


CREATE TABLE ORDER_LIST
(
	ORDER_MEMBER_EMAIL varchar2(35) NOT NULL UNIQUE,
	ORDER_ITEM_MODEL varchar2(200) NOT NULL UNIQUE,
	ORDER_ITEM_NAME varchar2(50) NOT NULL,
	ORDER_ITEM_AMOUNT number(5) NOT NULL,
	ORDER_ITEM_PRICE_SUM number(10) NOT NULL,
	ORDER_ITEM_BRAND varchar2(50) NOT NULL,
	ORDER_MEMBER_NAME varchar2(20) NOT NULL,
	ORDER_MEMBER_TEL varchar2(20) NOT NULL,
	ORDER_MEMBER_ZIP varchar2(10) NOT NULL,
	ORDER_MEMBER_ADDR_1 varchar2(50) NOT NULL,
	ORDER_MEMBER_ADDR_2 varchar2(50) NOT NULL,
	ORDER_NAME varchar2(20) NOT NULL,
	ORDER_TEL varchar2(20) NOT NULL,
	ORDER_ZIP varchar2(10) NOT NULL,
	ORDER_ADDR_1 varchar2(50) NOT NULL,
	ORDER_ADDR_2 varchar2(50) NOT NULL,
	ORDER_MEMO varchar2(500),
	ORDER_TRADE_TYPE varchar2(20) NOT NULL,
	ORDER_TRADE_PAYER varchar2(20) NOT NULL,
	ORDER_DATE date NOT NULL,
	ORDER_STATUS varchar2(10) NOT NULL,
	ORDER_TRADE_NUM varchar2(50) NOT NULL
);


CREATE TABLE QnA_BOARD
(
	QnA_MEMBER_EMAIL varchar2(35) NOT NULL UNIQUE,
	QnA_MEMBER_NAME varchar2(20) NOT NULL,
	QnA_NUM number(5) NOT NULL,
	QnA_SUBJECT varchar2(50) NOT NULL,
	QnA_CONTENT varchar2(2000) NOT NULL,
	QnA_DATE date NOT NULL,
	QnA_SEQ number(5),
	QnA_REF number(5),
	QnA_LEV number(5),
	QnA_READCOUNT number(5) NOT NULL,
	QnA_FILE varchar2(50)
);


CREATE TABLE REPLY
(
	REPLY_BOARD varchar2(10) NOT NULL,
	REPLY_MEMBER_EMAIL varchar2(35) NOT NULL UNIQUE,
	REPLY_MEMBER_NAME varchar2(20) NOT NULL,
	REPLY_CONTENT varchar2(200) NOT NULL,
	REPLY_DATE date NOT NULL,
	REPLY_SEQ number,
	REPLY_REF number,
	REPLY_LEV number
);


CREATE TABLE REVIEW
(
	REVIEW_MEMBER_EMAIL varchar2(35) NOT NULL UNIQUE,
	REVIEW_MEMBER_NAME varchar2(20) NOT NULL,
	REVIEW_SUBJECT varchar2(100) NOT NULL,
	REVIEW_CONTENT varchar2(2000) NOT NULL,
	REVIEW_READCOUNT number(5) NOT NULL,
	REVIEW_DATE date NOT NULL,
	REVIEW_NUM number(10) NOT NULL UNIQUE,
	REVIEW_SEQ number(5),
	REVIEW_LEV number(5),
	REVIEW_FILE varchar2(50)
);